version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development

  prod: 
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
